# Generated by Django 3.1.5 on 2021-03-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='organzition_id',
        ),
        migrations.RemoveField(
            model_name='customer_bill',
            name='cusotmer_id',
        ),
        migrations.RemoveField(
            model_name='customer_bill',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='customer_bill',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='inssurance_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='labs_prc_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='visa_id',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Customer_bill',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Inssurance',
        ),
        migrations.DeleteModel(
            name='Labs_pcr',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Organzition',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Visa',
        ),
    ]
