# Generated by Django 3.1.5 on 2021-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210318_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigservice',
            name='ser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bigservice',
            name='ser_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bigservice',
            name='ser_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='smallservice',
            name='ser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smallservice',
            name='ser_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
