# Generated by Django 3.1.5 on 2021-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210318_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ser_type',
            field=models.BooleanField(default=True),
        ),
    ]
