# Generated by Django 3.1.5 on 2021-03-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_ser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ser_type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
