# Generated by Django 3.1.5 on 2021-03-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210318_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
